name: Preview Build
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Preview
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build
        run: npm install && npm run build
      - name: Publish
        id: publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish build --project-name=discord-resources-wiki --branch=pr-${{ github.run_id }} --commit-dirty=true &> output.txt && echo "::set-output name=stdout::$(cat output.txt)"

      - name: Comment PR
        if: always()
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Test Deployment:
            ```sh
            ${{steps.publish.outputs.stdout}}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
